/* Machine Repository Implementation
 *
 * Copyright (c) 2026 The OSCAR Team
 *
 * This file implements the MachineRepository class for machine
 * database operations.
 *
 * This file is subject to the terms and conditions of the GNU General Public
 * License. See the file COPYING in the main directory of the source code
 * for more details. */

#include "machine_repository.h"
#include "database_manager.h"
#include <QSqlQuery>
#include <QSqlError>
#include <QVariant>
#include <QDebug>

/*
 * Constructor
 */
MachineRepository::MachineRepository()
{
}

/*
 * Destructor
 */
MachineRepository::~MachineRepository()
{
}

/*
 * Get the database connection from DatabaseManager
 *
 * Returns: QSqlDatabase instance
 */
QSqlDatabase MachineRepository::database()
{
    return DatabaseManager::instance().database();
}

/*
 * Create a new machine in the database
 *
 * Parameters:
 *   data - MachineData containing machine information
 *
 * Returns: Machine database ID if successful, -1 on error
 *
 * The id field in data is ignored (auto-generated by database).
 * The createdAt timestamp is set automatically by the database.
 */
qint64 MachineRepository::create(const MachineData& data)
{
    QSqlQuery query(database());
    
    query.prepare(
        "INSERT INTO machines ("
        "profile_id, machine_id, loader_name, machine_type, "
        "brand, model, series, serial_number, model_number, "
        "last_imported, purge_date, data_version, properties"
        ") VALUES ("
        ":profile_id, :machine_id, :loader_name, :machine_type, "
        ":brand, :model, :series, :serial_number, :model_number, "
        ":last_imported, :purge_date, :data_version, :properties"
        ")"
    );
    
    query.bindValue(":profile_id", data.profileId);
    query.bindValue(":machine_id", data.machineId);
    query.bindValue(":loader_name", data.loaderName);
    query.bindValue(":machine_type", data.machineType);
    query.bindValue(":brand", data.brand);
    query.bindValue(":model", data.model);
    query.bindValue(":series", data.series);
    query.bindValue(":serial_number", data.serialNumber);
    query.bindValue(":model_number", data.modelNumber);
    query.bindValue(":last_imported", data.lastImported);
    query.bindValue(":purge_date", data.purgeDate);
    query.bindValue(":data_version", data.dataVersion);
    query.bindValue(":properties", data.properties);
    
    if (!query.exec()) {
        qWarning() << "MachineRepository::create() failed:" << query.lastError().text();
        return -1;
    }
    
    qint64 id = query.lastInsertId().toLongLong();
    qDebug() << "MachineRepository: Created machine" << data.brand << data.model 
             << "serial" << data.serialNumber << "with id" << id;
    
    return id;
}

/*
 * Find a machine by database ID
 *
 * Parameters:
 *   id - Database primary key
 *
 * Returns: MachineData if found, or null MachineData (id=0) if not found
 */
MachineData MachineRepository::findById(qint64 id)
{
    QSqlQuery query(database());
    
    query.prepare(
        "SELECT id, profile_id, machine_id, loader_name, machine_type, "
        "brand, model, series, serial_number, model_number, "
        "last_imported, purge_date, data_version, properties, created_at "
        "FROM machines WHERE id = :id"
    );
    
    query.bindValue(":id", id);
    
    if (!query.exec()) {
        qWarning() << "MachineRepository::findById() failed:" << query.lastError().text();
        return MachineData();
    }
    
    if (query.next()) {
        return recordToData(query);
    }
    
    return MachineData();
}

/*
 * Find a machine by profile ID and machine ID
 *
 * Parameters:
 *   profileId - Profile database ID
 *   machineId - OSCAR machine ID
 *
 * Returns: MachineData if found, or null MachineData (id=0) if not found
 */
MachineData MachineRepository::findByProfileAndMachineId(qint64 profileId, qint64 machineId)
{
    QSqlQuery query(database());
    
    query.prepare(
        "SELECT id, profile_id, machine_id, loader_name, machine_type, "
        "brand, model, series, serial_number, model_number, "
        "last_imported, purge_date, data_version, properties, created_at "
        "FROM machines WHERE profile_id = :profile_id AND machine_id = :machine_id"
    );
    
    query.bindValue(":profile_id", profileId);
    query.bindValue(":machine_id", machineId);
    
    if (!query.exec()) {
        qWarning() << "MachineRepository::findByProfileAndMachineId() failed:" << query.lastError().text();
        return MachineData();
    }
    
    if (query.next()) {
        return recordToData(query);
    }
    
    return MachineData();
}

/*
 * Find a machine by serial number and loader name
 *
 * Parameters:
 *   serialNumber - Device serial number
 *   loaderName - Loader plugin name
 *
 * Returns: MachineData if found, or null MachineData (id=0) if not found
 */
MachineData MachineRepository::findBySerialAndLoader(const QString& serialNumber, const QString& loaderName)
{
    QSqlQuery query(database());
    
    query.prepare(
        "SELECT id, profile_id, machine_id, loader_name, machine_type, "
        "brand, model, series, serial_number, model_number, "
        "last_imported, purge_date, data_version, properties, created_at "
        "FROM machines WHERE serial_number = :serial_number AND loader_name = :loader_name"
    );
    
    query.bindValue(":serial_number", serialNumber);
    query.bindValue(":loader_name", loaderName);
    
    if (!query.exec()) {
        qWarning() << "MachineRepository::findBySerialAndLoader() failed:" << query.lastError().text();
        return MachineData();
    }
    
    if (query.next()) {
        return recordToData(query);
    }
    
    return MachineData();
}

/*
 * Get all machines for a specific profile
 *
 * Parameters:
 *   profileId - Profile database ID
 *
 * Returns: List of machine records for this profile, ordered by brand and model
 */
QList<MachineData> MachineRepository::findByProfile(qint64 profileId)
{
    QList<MachineData> machines;
    
    QSqlQuery query(database());
    
    query.prepare(
        "SELECT id, profile_id, machine_id, loader_name, machine_type, "
        "brand, model, series, serial_number, model_number, "
        "last_imported, purge_date, data_version, properties, created_at "
        "FROM machines WHERE profile_id = :profile_id "
        "ORDER BY brand, model"
    );
    
    query.bindValue(":profile_id", profileId);
    
    if (!query.exec()) {
        qWarning() << "MachineRepository::findByProfile() failed:" << query.lastError().text();
        return machines;
    }
    
    while (query.next()) {
        machines.append(recordToData(query));
    }
    
    qDebug() << "MachineRepository: Found" << machines.size() << "machines for profile" << profileId;
    
    return machines;
}

/*
 * Get all machines in database
 *
 * Returns: List of all machine records, ordered by profile_id, brand, and model
 */
QList<MachineData> MachineRepository::findAll()
{
    QList<MachineData> machines;
    
    QSqlQuery query(database());
    
    if (!query.exec(
        "SELECT id, profile_id, machine_id, loader_name, machine_type, "
        "brand, model, series, serial_number, model_number, "
        "last_imported, purge_date, data_version, properties, created_at "
        "FROM machines ORDER BY profile_id, brand, model"
    )) {
        qWarning() << "MachineRepository::findAll() failed:" << query.lastError().text();
        return machines;
    }
    
    while (query.next()) {
        machines.append(recordToData(query));
    }
    
    qDebug() << "MachineRepository: Found" << machines.size() << "machines total";
    
    return machines;
}

/*
 * Update an existing machine
 *
 * Parameters:
 *   data - MachineData with valid id field
 *
 * Returns: true if successful, false otherwise
 *
 * Updates all fields except id, profile_id, machine_id, and created_at.
 */
bool MachineRepository::update(const MachineData& data)
{
    if (data.id == 0) {
        qWarning() << "MachineRepository::update() - invalid id (0)";
        return false;
    }
    
    QSqlQuery query(database());
    
    query.prepare(
        "UPDATE machines SET "
        "loader_name = :loader_name, "
        "machine_type = :machine_type, "
        "brand = :brand, "
        "model = :model, "
        "series = :series, "
        "serial_number = :serial_number, "
        "model_number = :model_number, "
        "last_imported = :last_imported, "
        "purge_date = :purge_date, "
        "data_version = :data_version "
        "WHERE id = :id"
    );
    
    query.bindValue(":loader_name", data.loaderName);
    query.bindValue(":machine_type", data.machineType);
    query.bindValue(":brand", data.brand);
    query.bindValue(":model", data.model);
    query.bindValue(":series", data.series);
    query.bindValue(":serial_number", data.serialNumber);
    query.bindValue(":model_number", data.modelNumber);
    query.bindValue(":last_imported", data.lastImported);
    query.bindValue(":purge_date", data.purgeDate);
    query.bindValue(":data_version", data.dataVersion);
    query.bindValue(":id", data.id);
    
    if (!query.exec()) {
        qWarning() << "MachineRepository::update() failed:" << query.lastError().text();
        return false;
    }
    
    if (query.numRowsAffected() == 0) {
        qWarning() << "MachineRepository::update() - no machine found with id" << data.id;
        return false;
    }
    
    qDebug() << "MachineRepository: Updated machine id" << data.id;
    return true;
}

/*
 * Delete a machine from database
 *
 * Parameters:
 *   id - Database primary key of machine to delete
 *
 * Returns: true if successful, false otherwise
 */
bool MachineRepository::remove(qint64 id)
{
    if (id == 0) {
        qWarning() << "MachineRepository::remove() - invalid id (0)";
        return false;
    }
    
    QSqlQuery query(database());
    
    query.prepare("DELETE FROM machines WHERE id = :id");
    query.bindValue(":id", id);
    
    if (!query.exec()) {
        qWarning() << "MachineRepository::remove() failed:" << query.lastError().text();
        return false;
    }
    
    if (query.numRowsAffected() == 0) {
        qWarning() << "MachineRepository::remove() - no machine found with id" << id;
        return false;
    }
    
    qDebug() << "MachineRepository: Removed machine id" << id;
    return true;
}

/*
 * Check if a machine exists
 *
 * Parameters:
 *   profileId - Profile database ID
 *   machineId - OSCAR machine ID
 *
 * Returns: true if exists, false otherwise
 */
bool MachineRepository::exists(qint64 profileId, qint64 machineId)
{
    QSqlQuery query(database());
    
    query.prepare(
        "SELECT COUNT(*) FROM machines "
        "WHERE profile_id = :profile_id AND machine_id = :machine_id"
    );
    
    query.bindValue(":profile_id", profileId);
    query.bindValue(":machine_id", machineId);
    
    if (!query.exec()) {
        qWarning() << "MachineRepository::exists() failed:" << query.lastError().text();
        return false;
    }
    
    if (query.next()) {
        return query.value(0).toInt() > 0;
    }
    
    return false;
}

/*
 * Get count of machines for a profile
 *
 * Parameters:
 *   profileId - Profile database ID (0 = all profiles)
 *
 * Returns: Number of machine records
 */
int MachineRepository::count(qint64 profileId)
{
    QSqlQuery query(database());
    
    if (profileId == 0) {
        if (!query.exec("SELECT COUNT(*) FROM machines")) {
            qWarning() << "MachineRepository::count() failed:" << query.lastError().text();
            return 0;
        }
    } else {
        query.prepare("SELECT COUNT(*) FROM machines WHERE profile_id = :profile_id");
        query.bindValue(":profile_id", profileId);
        
        if (!query.exec()) {
            qWarning() << "MachineRepository::count() failed:" << query.lastError().text();
            return 0;
        }
    }
    
    if (query.next()) {
        return query.value(0).toInt();
    }
    
    return 0;
}

/*
 * Convert QSqlQuery result to MachineData
 *
 * Parameters:
 *   query - Query positioned at a result row
 *
 * Returns: MachineData populated from current row
 *
 * Expected column order:
 * id, profile_id, machine_id, loader_name, machine_type,
 * brand, model, series, serial_number, model_number,
 * last_imported, purge_date, data_version, properties, created_at
 */
MachineData MachineRepository::recordToData(QSqlQuery& query)
{
    MachineData data;
    
    data.id = query.value(0).toLongLong();
    data.profileId = query.value(1).toLongLong();
    data.machineId = query.value(2).toLongLong();
    data.loaderName = query.value(3).toString();
    data.machineType = query.value(4).toInt();
    data.brand = query.value(5).toString();
    data.model = query.value(6).toString();
    data.series = query.value(7).toString();
    data.serialNumber = query.value(8).toString();
    data.modelNumber = query.value(9).toString();
    data.lastImported = query.value(10).toString();
    data.purgeDate = query.value(11).toString();
    data.dataVersion = query.value(12).toInt();
    data.properties = query.value(13).toString();
    data.createdAt = query.value(14).toString();
    
    return data;
}
