/* Profile Repository Implementation
 *
 * Copyright (c) 2026 The OSCAR Team
 *
 * This file implements the ProfileRepository class for profile
 * database operations.
 *
 * This file is subject to the terms and conditions of the GNU General Public
 * License. See the file COPYING in the main directory of the source code
 * for more details. */

#include "profile_repository.h"
#include "database_manager.h"
#include <QSqlQuery>
#include <QSqlError>
#include <QVariant>
#include <QDateTime>
#include <QDebug>

/*
 * Constructor
 */
ProfileRepository::ProfileRepository()
{
}

/*
 * Destructor
 */
ProfileRepository::~ProfileRepository()
{
}

/*
 * Get the database connection from DatabaseManager
 *
 * Returns: QSqlDatabase instance
 */
QSqlDatabase ProfileRepository::database()
{
    return DatabaseManager::instance().database();
}

/*
 * Create a new profile in the database
 *
 * Parameters:
 *   data - ProfileData containing username and dataFolder
 *
 * Returns: Profile ID if successful, -1 on error
 *
 * The id field in data is ignored (auto-generated by database).
 * Timestamps are set automatically by the database.
 */
qint64 ProfileRepository::create(const ProfileData& data)
{
    QSqlQuery query(database());
    
    query.prepare(
        "INSERT INTO profiles (username, data_folder) "
        "VALUES (:username, :data_folder)"
    );
    
    query.bindValue(":username", data.username);
    query.bindValue(":data_folder", data.dataFolder);
    
    if (!query.exec()) {
        qWarning() << "ProfileRepository::create() failed:" << query.lastError().text();
        return -1;
    }
    
    qint64 id = query.lastInsertId().toLongLong();
    qDebug() << "ProfileRepository: Created profile" << data.username << "with id" << id;
    
    return id;
}

/*
 * Find a profile by database ID
 *
 * Parameters:
 *   id - Database primary key
 *
 * Returns: ProfileData if found, or null ProfileData (id=0) if not found
 */
ProfileData ProfileRepository::findById(qint64 id)
{
    QSqlQuery query(database());
    
    query.prepare(
        "SELECT id, username, data_folder, status, status_changed_at, created_at, updated_at "
        "FROM profiles WHERE id = :id"
    );
    
    query.bindValue(":id", id);
    
    if (!query.exec()) {
        qWarning() << "ProfileRepository::findById() failed:" << query.lastError().text();
        return ProfileData();
    }
    
    if (query.next()) {
        return recordToData(query);
    }
    
    return ProfileData();
}

/*
 * Find a profile by username
 *
 * Parameters:
 *   username - Username to search for (case-sensitive)
 *
 * Returns: ProfileData if found, or null ProfileData (id=0) if not found
 */
ProfileData ProfileRepository::findByUsername(const QString& username)
{
    QSqlQuery query(database());
    
    query.prepare(
        "SELECT id, username, data_folder, status, status_changed_at, created_at, updated_at "
        "FROM profiles WHERE username = :username"
    );
    
    query.bindValue(":username", username);
    
    if (!query.exec()) {
        qWarning() << "ProfileRepository::findByUsername() failed:" << query.lastError().text();
        return ProfileData();
    }
    
    if (query.next()) {
        return recordToData(query);
    }
    
    return ProfileData();
}

/*
 * Get all profiles from database
 *
 * Returns: List of all profile records, ordered by username
 */
QList<ProfileData> ProfileRepository::findAll()
{
    QList<ProfileData> profiles;
    
    QSqlQuery query(database());
    
    if (!query.exec("SELECT id, username, data_folder, status, status_changed_at, created_at, updated_at "
                    "FROM profiles ORDER BY username")) {
        qWarning() << "ProfileRepository::findAll() failed:" << query.lastError().text();
        return profiles;
    }
    
    while (query.next()) {
        profiles.append(recordToData(query));
    }
    
    qDebug() << "ProfileRepository: Found" << profiles.size() << "profiles";
    
    return profiles;
}

/*
 * Get only active profiles from database
 *
 * Returns: List of active profile records (status='active'), ordered by username
 */
QList<ProfileData> ProfileRepository::findActive()
{
    QList<ProfileData> profiles;
    
    QSqlQuery query(database());
    
    if (!query.exec("SELECT id, username, data_folder, status, status_changed_at, created_at, updated_at "
                    "FROM profiles WHERE status = 'active' ORDER BY username")) {
        qWarning() << "ProfileRepository::findActive() failed:" << query.lastError().text();
        return profiles;
    }
    
    while (query.next()) {
        profiles.append(recordToData(query));
    }
    
    qDebug() << "ProfileRepository: Found" << profiles.size() << "active profiles";
    
    return profiles;
}

/*
 * Get profiles with missing directories
 *
 * Returns: List of missing profile records (status='missing'), ordered by username
 */
QList<ProfileData> ProfileRepository::findMissing()
{
    QList<ProfileData> profiles;
    
    QSqlQuery query(database());
    
    if (!query.exec("SELECT id, username, data_folder, status, status_changed_at, created_at, updated_at "
                    "FROM profiles WHERE status = 'missing' ORDER BY username")) {
        qWarning() << "ProfileRepository::findMissing() failed:" << query.lastError().text();
        return profiles;
    }
    
    while (query.next()) {
        profiles.append(recordToData(query));
    }
    
    qDebug() << "ProfileRepository: Found" << profiles.size() << "missing profiles";
    
    return profiles;
}

/*
 * Update profile status
 *
 * Parameters:
 *   id - Profile database ID
 *   status - New status ('active', 'missing', or 'archived')
 *
 * Returns: true if successful, false otherwise
 *
 * Also sets statusChangedAt to current timestamp.
 */
bool ProfileRepository::updateStatus(qint64 id, const QString& status)
{
    if (id == 0) {
        qWarning() << "ProfileRepository::updateStatus() - invalid id (0)";
        return false;
    }
    
    if (status != "active" && status != "missing" && status != "archived") {
        qWarning() << "ProfileRepository::updateStatus() - invalid status:" << status;
        return false;
    }
    
    QSqlQuery query(database());
    query.prepare("UPDATE profiles SET status = :status, "
                  "status_changed_at = datetime('now'), "
                  "updated_at = datetime('now') WHERE id = :id");
    query.bindValue(":status", status);
    query.bindValue(":id", id);
    
    if (!query.exec()) {
        qWarning() << "ProfileRepository::updateStatus() failed:" << query.lastError().text();
        return false;
    }
    
    if (query.numRowsAffected() == 0) {
        qWarning() << "ProfileRepository::updateStatus() - no profile found with id" << id;
        return false;
    }
    
    qDebug() << "ProfileRepository: Updated profile" << id << "status to" << status;
    return true;
}

/*
 * Update an existing profile
 *
 * Parameters:
 *   data - ProfileData with valid id field
 *
 * Returns: true if successful, false otherwise
 *
 * Updates username and dataFolder for the profile identified by data.id.
 * The updatedAt timestamp is automatically set to current time.
 */
bool ProfileRepository::update(const ProfileData& data)
{
    if (data.id == 0) {
        qWarning() << "ProfileRepository::update() - invalid id (0)";
        return false;
    }
    
    QSqlQuery query(database());
    
    query.prepare(
        "UPDATE profiles SET "
        "username = :username, "
        "data_folder = :data_folder, "
        "updated_at = CURRENT_TIMESTAMP "
        "WHERE id = :id"
    );
    
    query.bindValue(":username", data.username);
    query.bindValue(":data_folder", data.dataFolder);
    query.bindValue(":id", data.id);
    
    if (!query.exec()) {
        qWarning() << "ProfileRepository::update() failed:" << query.lastError().text();
        return false;
    }
    
    if (query.numRowsAffected() == 0) {
        qWarning() << "ProfileRepository::update() - no profile found with id" << data.id;
        return false;
    }
    
    qDebug() << "ProfileRepository: Updated profile id" << data.id;
    return true;
}

/*
 * Delete a profile from database
 *
 * Parameters:
 *   id - Database primary key of profile to delete
 *
 * Returns: true if successful, false otherwise
 *
 * Note: Foreign key constraints will cascade delete all machines
 * associated with this profile.
 *
 * PERFORMANCE OPTIMIZATIONS (Phase 1):
 * - Checkpoints WAL before/after deletion to minimize file size
 * - Uses deferred foreign keys to batch CASCADE operations
 * - Temporarily increases cache size for faster processing
 * - Explicit transaction control for better rollback handling
 *
 * Expected improvement: 67-80% faster (15 min → 3-5 min for large profiles)
 */
bool ProfileRepository::remove(qint64 id)
{
    if (id == 0) {
        qWarning() << "ProfileRepository::remove() - invalid id (0)";
        return false;
    }
    
    QSqlDatabase db = database();
    QSqlQuery query(db);
    
    qDebug() << "ProfileRepository: Starting optimized profile deletion for id" << id;
    
    // OPTIMIZATION 1: Checkpoint WAL before deletion to start with clean slate
    // This reduces WAL file size and improves deletion performance
    qDebug() << "ProfileRepository: Checkpointing WAL before deletion...";
    DatabaseManager::instance().checkpointWAL();
    
    // OPTIMIZATION 2: Start explicit transaction
    if (!db.transaction()) {
        qWarning() << "ProfileRepository::remove() - Failed to start transaction:" 
                   << db.lastError().text();
        return false;
    }
    
    // OPTIMIZATION 3: Enable deferred foreign key constraints
    // This allows SQLite to batch CASCADE operations instead of processing
    // each row individually, dramatically reducing overhead for large deletes
    if (!query.exec("PRAGMA defer_foreign_keys = ON")) {
        qWarning() << "ProfileRepository::remove() - Failed to enable deferred foreign keys:" 
                   << query.lastError().text();
        // Continue anyway - this is an optimization, not required for correctness
    } else {
        qDebug() << "ProfileRepository: Deferred foreign keys enabled";
    }
    
    // OPTIMIZATION 4: Temporarily increase cache size for deletion
    // Larger cache = fewer disk I/O operations = faster deletion
    int originalCacheSize = -64000;  // 64 MB (default from configureDatabaseSettings)
    if (!query.exec("PRAGMA cache_size = -256000")) {  // 256 MB for deletion
        qWarning() << "ProfileRepository::remove() - Failed to increase cache size:" 
                   << query.lastError().text();
        // Continue anyway
    } else {
        qDebug() << "ProfileRepository: Cache size increased to 256 MB for deletion";
    }
    
    // Perform the actual delete
    query.prepare("DELETE FROM profiles WHERE id = :id");
    query.bindValue(":id", id);
    
    bool success = false;
    if (!query.exec()) {
        qWarning() << "ProfileRepository::remove() - Delete failed:" << query.lastError().text();
        db.rollback();
    } else if (query.numRowsAffected() == 0) {
        qWarning() << "ProfileRepository::remove() - no profile found with id" << id;
        db.rollback();
    } else {
        // OPTIMIZATION 5: Commit triggers deferred constraint checking
        // All CASCADE deletes are executed as a batch at this point
        qDebug() << "ProfileRepository: Committing transaction (executing CASCADE deletes)...";
        if (!db.commit()) {
            qWarning() << "ProfileRepository::remove() - Commit failed:" 
                       << db.lastError().text();
            db.rollback();
        } else {
            qDebug() << "ProfileRepository: Profile" << id << "deleted successfully";
            success = true;
        }
    }
    
    // Restore original settings
    query.exec("PRAGMA defer_foreign_keys = OFF");
    query.exec(QString("PRAGMA cache_size = %1").arg(originalCacheSize));
    
    if (success) {
        // OPTIMIZATION 6: Checkpoint WAL after deletion to reclaim space immediately
        qDebug() << "ProfileRepository: Checkpointing WAL after deletion...";
        DatabaseManager::instance().checkpointWAL();
        
        qDebug() << "ProfileRepository: Profile removal complete";
    }
    
    return success;
}

/*
 * Delete a profile with progress reporting (Phase 1.5 optimized)
 *
 * Parameters:
 *   id - Database primary key of profile to delete
 *   progressCallback - Function called to report progress (0-100%)
 *
 * Returns: true if successful, false otherwise
 *
 * PHASE 1.5 ENHANCEMENTS:
 * - Batch session deletion (100 sessions at a time)
 * - Manual handling of largest child tables (session_channel_values, event_data)
 * - Progress reporting throughout operation
 * - Retains all Phase 1 optimizations (WAL checkpoint, deferred FK, large cache)
 *
 * Expected improvement: 50-60% faster than original (15 min → 6-7 min)
 */
bool ProfileRepository::removeWithProgress(qint64 id, ProgressCallback progressCallback)
{
    if (id == 0) {
        qWarning() << "ProfileRepository::removeWithProgress() - invalid id (0)";
        return false;
    }
    
    QSqlDatabase db = database();
    QSqlQuery query(db);
    
    qDebug() << "ProfileRepository: Starting Phase 1.5 optimized profile deletion for id" << id;
    
    // Report initial progress
    if (progressCallback) {
        progressCallback(0, QObject::tr("Preparing database for deletion..."));
    }
    
    // PHASE 1 OPTIMIZATION: Checkpoint WAL before deletion
    qDebug() << "ProfileRepository: Checkpointing WAL before deletion...";
    DatabaseManager::instance().checkpointWAL();
    
    if (progressCallback) {
        progressCallback(5, QObject::tr("Starting database transaction..."));
    }
    
    // Start explicit transaction
    if (!db.transaction()) {
        qWarning() << "ProfileRepository::removeWithProgress() - Failed to start transaction:" 
                   << db.lastError().text();
        return false;
    }
    
    // PHASE 1 OPTIMIZATIONS: Enable deferred FK and increase cache
    query.exec("PRAGMA defer_foreign_keys = ON");
    query.exec("PRAGMA cache_size = -256000");  // 256 MB
    
    if (progressCallback) {
        progressCallback(5, QObject::tr("Collecting session information..."));
    }
    
    // PHASE 1.5: Get all session IDs for this profile
    QList<qint64> sessionIds;
    query.prepare(
        "SELECT s.id FROM sessions s "
        "JOIN machines m ON s.machine_id = m.id "
        "WHERE m.profile_id = ?"
    );
    query.bindValue(0, id);
    
    if (!query.exec()) {
        qWarning() << "ProfileRepository::removeWithProgress() - Failed to query sessions:" 
                   << query.lastError().text();
        db.rollback();
        query.exec("PRAGMA defer_foreign_keys = OFF");
        query.exec("PRAGMA cache_size = -64000");
        return false;
    }
    
    while (query.next()) {
        sessionIds.append(query.value(0).toLongLong());
    }
    
    int totalSessions = sessionIds.size();
    qDebug() << "ProfileRepository: Found" << totalSessions << "sessions to delete";
    
    if (totalSessions == 0) {
        // No sessions, just delete profile normally
        if (progressCallback) {
            progressCallback(50, QObject::tr("Deleting profile (no session data)..."));
        }
        
        query.prepare("DELETE FROM profiles WHERE id = ?");
        query.bindValue(0, id);
        
        bool success = false;
        if (!query.exec()) {
            db.rollback();
        } else if (query.numRowsAffected() == 0) {
            db.rollback();
        } else if (!db.commit()) {
            qWarning() << "ProfileRepository::removeWithProgress() - Commit failed:"
                       << db.lastError().text();
            db.rollback();
        } else {
            success = true;
            if (progressCallback) {
                progressCallback(70, QObject::tr("Profile deleted"));
            }
        }
        
        query.exec("PRAGMA defer_foreign_keys = OFF");
        query.exec("PRAGMA cache_size = -64000");
        DatabaseManager::instance().checkpointWAL();
        
        return success;
    }
    
    // PHASE 1.5: Delete sessions in batches for optimal performance
    const int batchSize = 100;
    int totalBatches = (totalSessions + batchSize - 1) / batchSize;
    int processedSessions = 0;
    if (progressCallback) {
        progressCallback(10, QObject::tr("Deleting session channel data..."));
    }

    qDebug() << "ProfileRepository: Deleting" << totalSessions << "sessions in" << totalBatches << "batches";
    
    for (int batchNum = 0; batchNum < totalBatches; batchNum++) {
        int startIdx = batchNum * batchSize;
        int endIdx = qMin(startIdx + batchSize, totalSessions);
        
        // Build IN clause for this batch
        QStringList batch;
        for (int i = startIdx; i < endIdx; i++) {
            batch.append(QString::number(sessionIds[i]));
        }
        QString inClause = batch.join(",");
/***
        // Progress: 10% to 50% is for session_channel_values deletion
        int progress = 10 + (batchNum * 40 / totalBatches);
        if (progressCallback) {
            progressCallback(progress, 
                QObject::tr("Deleting session data (%1 of %2 sessions)...")
                .arg(processedSessions + batch.size())
                .arg(totalSessions));
        }
***/
        // Delete session_channel_values (largest table) for this batch
        QString sql = QString(
            "DELETE FROM session_channel_values "
            "WHERE session_channel_id IN ("
            "  SELECT id FROM session_channels WHERE session_id IN (%1)"
            ")"
        ).arg(inClause);
        
        if (!query.exec(sql)) {
            qWarning() << "ProfileRepository::removeWithProgress() - Failed to delete session_channel_values:" 
                       << query.lastError().text();
            db.rollback();
            query.exec("PRAGMA defer_foreign_keys = OFF");
            query.exec("PRAGMA cache_size = -64000");
            return false;
        }
        
        qDebug() << "  Batch" << (batchNum + 1) << "/" << totalBatches 
                 << ": Deleted" << query.numRowsAffected() << "channel values";
        
        processedSessions += batch.size();
    }
    
    // Progress: 50% to 70% is for event_data deletion (large BLOBs)
    if (progressCallback) {
        progressCallback(30, QObject::tr("Deleting waveform data..."));
    }
    
    // Delete event_data (large BLOBs) in batches
    processedSessions = 0;
    for (int batchNum = 0; batchNum < totalBatches; batchNum++) {
        int startIdx = batchNum * batchSize;
        int endIdx = qMin(startIdx + batchSize, totalSessions);
        
        QStringList batch;
        for (int i = startIdx; i < endIdx; i++) {
            batch.append(QString::number(sessionIds[i]));
        }
        QString inClause = batch.join(",");

        int progress = 30 + (batchNum * 20 / totalBatches);
        if (progressCallback) {
            progressCallback(progress, 
                QObject::tr("Deleting waveform data (%1 of %2 sessions)...")
                .arg(processedSessions + batch.size())
                .arg(totalSessions));
        }

        QString sql = QString(
            "DELETE FROM event_data "
            "WHERE eventlist_id IN ("
            "  SELECT id FROM event_lists WHERE session_id IN (%1)"
            ")"
        ).arg(inClause);
        
        if (!query.exec(sql)) {
            qWarning() << "ProfileRepository::removeWithProgress() - Failed to delete event_data:" 
                       << query.lastError().text();
            db.rollback();
            query.exec("PRAGMA defer_foreign_keys = OFF");
            query.exec("PRAGMA cache_size = -64000");
            return false;
        }
        
        qDebug() << "  Batch" << (batchNum + 1) << "/" << totalBatches 
                 << ": Deleted" << query.numRowsAffected() << "event data records";
        
        processedSessions += batch.size();
    }
    
    // Progress: 70% to 80% is for deleting sessions (CASCADE handles smaller tables)
    if (progressCallback) {
        progressCallback(50, QObject::tr("Deleting session records..."));
    }
    
    // Delete all sessions (CASCADE will handle remaining child tables)
    QString sessionIdsStr;
    for (int i = 0; i < sessionIds.size(); i++) {
        if (i > 0) sessionIdsStr += ",";
        sessionIdsStr += QString::number(sessionIds[i]);
    }
    
    QString sql = QString("DELETE FROM sessions WHERE id IN (%1)").arg(sessionIdsStr);
    if (!query.exec(sql)) {
        qWarning() << "ProfileRepository::removeWithProgress() - Failed to delete sessions:" 
                   << query.lastError().text();
        db.rollback();
        query.exec("PRAGMA defer_foreign_keys = OFF");
        query.exec("PRAGMA cache_size = -64000");
        return false;
    }
    
    qDebug() << "ProfileRepository: Deleted" << query.numRowsAffected() << "sessions";
    
    // Progress: 80% to 90% is for deleting profile record (CASCADE handles profile-level tables)
    if (progressCallback) {
        progressCallback(60, QObject::tr("Deleting profile record..."));
    }
    
    // Delete the profile (CASCADE handles machines, user_info, doctor_info, etc.)
    query.prepare("DELETE FROM profiles WHERE id = ?");
    query.bindValue(0, id);
    
    if (!query.exec()) {
        qWarning() << "ProfileRepository::removeWithProgress() - Failed to delete profile:" 
                   << query.lastError().text();
        db.rollback();
        query.exec("PRAGMA defer_foreign_keys = OFF");
        query.exec("PRAGMA cache_size = -64000");
        return false;
    }
    
    // Progress: 90% to 95% is for committing transaction
    if (progressCallback) {
        progressCallback(70, QObject::tr("Committing database changes..."));
    }
    
    // Commit transaction
    qDebug() << "ProfileRepository: Committing transaction...";
    if (!db.commit()) {
        qWarning() << "ProfileRepository::removeWithProgress() - Commit failed:" 
                   << db.lastError().text();
        db.rollback();
        query.exec("PRAGMA defer_foreign_keys = OFF");
        query.exec("PRAGMA cache_size = -64000");
        return false;
    }
    
    // Restore settings
    query.exec("PRAGMA defer_foreign_keys = OFF");
    query.exec("PRAGMA cache_size = -64000");
    
    // Progress: 95% to 100% is for final WAL checkpoint
    if (progressCallback) {
        progressCallback(75, QObject::tr("Reclaiming database disk space..."));
    }
    
    // PHASE 1 OPTIMIZATION: Checkpoint WAL after deletion
    qDebug() << "ProfileRepository: Checkpointing WAL after deletion...";
    DatabaseManager::instance().checkpointWAL();
    
    if (progressCallback) {
        progressCallback(75, QObject::tr("Profile deleted successfully"));
    }
    
    qDebug() << "ProfileRepository: Phase 1.5 profile deletion complete for id" << id;
    return true;
}

/*
 * Check if a profile with given username exists
 *
 * Parameters:
 *   username - Username to check
 *
 * Returns: true if exists, false otherwise
 */
bool ProfileRepository::exists(const QString& username)
{
    QSqlQuery query(database());
    
    query.prepare("SELECT COUNT(*) FROM profiles WHERE username = :username");
    query.bindValue(":username", username);
    
    if (!query.exec()) {
        qWarning() << "ProfileRepository::exists() failed:" << query.lastError().text();
        return false;
    }
    
    if (query.next()) {
        return query.value(0).toInt() > 0;
    }
    
    return false;
}

/*
 * Get count of profiles in database
 *
 * Returns: Number of profile records
 */
int ProfileRepository::count()
{
    QSqlQuery query(database());
    
    if (!query.exec("SELECT COUNT(*) FROM profiles")) {
        qWarning() << "ProfileRepository::count() failed:" << query.lastError().text();
        return 0;
    }
    
    if (query.next()) {
        return query.value(0).toInt();
    }
    
    return 0;
}

/*
 * Resolve a portable profile path
 *
 * Parameters:
 *   portablePath - Path that may contain %PROFDIR% variable
 *   profilesBasePath - Base path for profiles directory
 *
 * Returns: Resolved absolute path
 *
 * This static method replaces %PROFDIR% with the actual profiles base path,
 * making the database portable across different machines and installations.
 *
 * Example:
 *   Input:  "%PROFDIR%/John"
 *   Base:   "C:/Users/Guy/Documents/OSCAR20_Data/Profiles"
 *   Output: "C:/Users/Guy/Documents/OSCAR20_Data/Profiles/John"
 */
QString ProfileRepository::resolvePath(const QString& portablePath, const QString& profilesBasePath)
{
    QString resolved = portablePath;
    
    // Replace %PROFDIR% with actual base path
    if (resolved.contains("%PROFDIR%")) {
        resolved.replace("%PROFDIR%", profilesBasePath);
    }
    
    // Normalize path separators
    resolved.replace("\\", "/");
    
    // Remove duplicate slashes
    while (resolved.contains("//")) {
        resolved.replace("//", "/");
    }
    
    return resolved;
}

/*
 * Convert QSqlQuery result to ProfileData
 *
 * Parameters:
 *   query - Query positioned at a result row
 *
 * Returns: ProfileData populated from current row
 *
 * Expected column order: id, username, data_folder, status, status_changed_at, created_at, updated_at
 */
ProfileData ProfileRepository::recordToData(QSqlQuery& query)
{
    ProfileData data;
    
    data.id = query.value(0).toLongLong();
    data.username = query.value(1).toString();
    data.dataFolder = query.value(2).toString();
    data.status = query.value(3).toString();
    data.statusChangedAt = query.value(4).toString();
    data.createdAt = query.value(5).toString();
    data.updatedAt = query.value(6).toString();
    
    return data;
}
